config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  root "posts#index"
  resources :posts do
      resources :comments
      member do
          get 'like'
          get 'unlike'
      end
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
=begin
                  Prefix Verb   URI Pattern                                 Controller#Action
           profiles_show GET    /profiles/show(.:format)                    profiles#show
        new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
            user_session POST   /users/sign_in(.:format)                    devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
           user_password POST   /users/password(.:format)                   devise/passwords#create
       new_user_password GET    /users/password/new(.:format)               devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
                         PATCH  /users/password(.:format)                   devise/passwords#update
                         PUT    /users/password(.:format)                   devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                     registrations#cancel
       user_registration POST   /users(.:format)                            registrations#create
   new_user_registration GET    /users/sign_up(.:format)                    registrations#new
  edit_user_registration GET    /users/edit(.:format)                       registrations#edit
                         PATCH  /users(.:format)                            registrations#update
                         PUT    /users(.:format)                            registrations#update
                         DELETE /users(.:format)                            registrations#destroy
                    root GET    /                                           posts#index
           post_comments GET    /posts/:post_id/comments(.:format)          comments#index
                         POST   /posts/:post_id/comments(.:format)          comments#create
        new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
       edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
            post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
                         PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
                         PUT    /posts/:post_id/comments/:id(.:format)      comments#update
                         DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
               like_post GET    /posts/:id/like(.:format)                   posts#like
             unlike_post GET    /posts/:id/unlike(.:format)                 posts#unlike
                   posts GET    /posts(.:format)                            posts#index
                         POST   /posts(.:format)                            posts#create
                new_post GET    /posts/new(.:format)                        posts#new
               edit_post GET    /posts/:id/edit(.:format)                   posts#edit
                    post GET    /posts/:id(.:format)                        posts#show
                         PATCH  /posts/:id(.:format)                        posts#update
                         PUT    /posts/:id(.:format)                        posts#update
                         DELETE /posts/:id(.:format)                        posts#destroy
                 profile GET    /:user_name(.:format)                       profiles#show
            edit_profile GET    /:user_name/edit(.:format)                  profiles#edit
          update_profile PATCH  /:user_name/edit(.:format)                  profiles#update
=end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update]
  before_action :owned_profile, only: [:edit, :update]
  
  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
  
  def edit
    
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = "Profile updated."
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash.now[:alert] = "Profile not updated."
      render :edit
    end
  end
  
  private
    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end
    
    def set_user
      @user = User.find_by(user_name: params[:user_name])
    end
    
    def owned_profile
      unless current_user == @user
        flash[:alert] = "That profile doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= image_tag @user.avatar.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image' if @user.avatar.exists? %>
        <%= form_for @user, url: {action: "update" }, html: { multipart: true }  do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="img-circle">
                <%= image_tag "placeholder.jpg", id: 'image-preview', class: 'img-responsive img-circle profile' %>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <%= f.text_area :bio, label: false, placeholder: "Bio", rows: 6 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn-success btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/_post.html.erb
<div class="posts-wrapper row">
  <div class="post">
      <div class="post-head">
        <div class="thumb-img">
          <div class="user-name">
  	      <%= post.user.user_name %>
          </div>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <div class="post-bottom">
        <p class="caption">
          <%= post.caption %>
        </p>
        <div class="time-ago">
          <%= time_ago_in_words(post.created_at) %>
        </div>
        <div class="comments" id="comments_#{post.id}">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
        <div class="comment-form row">
          <div class="like-button col-sm-11">
            <span class="glyphicon glyphicon-heart-empty"></span>
          </div>
          <div class="comment-form col-sm-11">
            <%= form_for [post, post.comments.build] do |f| %>
                <%= f.text_field :content, placeholder: 'Add a comment:', class: "comment_content", id: "comment_content_#{post.id}" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/profiles/edit.html.erb
<div class="text-center">
  <h1>Change your profile image:</h1>
</div>

<%= render "form" %>


<div class="text-center edit-links">
  <%= link_to "Back", profile_path(@user.user_name) %>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= image_tag @user.avatar.url(:medium), id: 'image-preview', class: 'img-responsive img-circle profile-image' if @user.avatar.exists? %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if current_user == @user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name), class: 'btn edit-button' %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <%= pluralize @user.posts.count, 'post' %>
      </div>
    </div>
  </div>
</div>
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
  <div class="text-center edit-links">
    <% if current_user.id == post.user.id %>
      <%= link_to "Edit post", edit_post_path(post) %>
    <% end %>
  </div>
<% end %>
<div class="text-center edit-links">
  <%= link_to "Back", posts_path %>
</div>