config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  root "posts#index"
  resources :posts do
      resources :comments
      member do
          get 'like'
          get 'unlike'
      end
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
=begin
                  Prefix Verb   URI Pattern                                 Controller#Action
           profiles_show GET    /profiles/show(.:format)                    profiles#show
        new_user_session GET    /users/sign_in(.:format)                    devise/sessions#new
            user_session POST   /users/sign_in(.:format)                    devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                   devise/sessions#destroy
           user_password POST   /users/password(.:format)                   devise/passwords#create
       new_user_password GET    /users/password/new(.:format)               devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)              devise/passwords#edit
                         PATCH  /users/password(.:format)                   devise/passwords#update
                         PUT    /users/password(.:format)                   devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                     registrations#cancel
       user_registration POST   /users(.:format)                            registrations#create
   new_user_registration GET    /users/sign_up(.:format)                    registrations#new
  edit_user_registration GET    /users/edit(.:format)                       registrations#edit
                         PATCH  /users(.:format)                            registrations#update
                         PUT    /users(.:format)                            registrations#update
                         DELETE /users(.:format)                            registrations#destroy
                    root GET    /                                           posts#index
           post_comments GET    /posts/:post_id/comments(.:format)          comments#index
                         POST   /posts/:post_id/comments(.:format)          comments#create
        new_post_comment GET    /posts/:post_id/comments/new(.:format)      comments#new
       edit_post_comment GET    /posts/:post_id/comments/:id/edit(.:format) comments#edit
            post_comment GET    /posts/:post_id/comments/:id(.:format)      comments#show
                         PATCH  /posts/:post_id/comments/:id(.:format)      comments#update
                         PUT    /posts/:post_id/comments/:id(.:format)      comments#update
                         DELETE /posts/:post_id/comments/:id(.:format)      comments#destroy
               like_post GET    /posts/:id/like(.:format)                   posts#like
             unlike_post GET    /posts/:id/unlike(.:format)                 posts#unlike
                   posts GET    /posts(.:format)                            posts#index
                         POST   /posts(.:format)                            posts#create
                new_post GET    /posts/new(.:format)                        posts#new
               edit_post GET    /posts/:id/edit(.:format)                   posts#edit
                    post GET    /posts/:id(.:format)                        posts#show
                         PATCH  /posts/:id(.:format)                        posts#update
                         PUT    /posts/:id(.:format)                        posts#update
                         DELETE /posts/:id(.:format)                        posts#destroy
                 profile GET    /:user_name(.:format)                       profiles#show
            edit_profile GET    /:user_name/edit(.:format)                  profiles#edit
          update_profile PATCH  /:user_name/edit(.:format)                  profiles#update
=end
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  has_attached_file :image, styles: { :medium => "640x" }
  validates :image, presence: true
  validates :caption, presence: true, length: { minimum: 3, maximum: 300 }
  validates :user_id, presence: true
  
  belongs_to :user, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]
  
  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end
  
  def new
    @post = current_user.posts.build
  end

  def create
    
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created."
      redirect_to posts_path
    else
      flash.now[:alert] = "Post not created."
      render :new
    end
    
  end

  def show
  end
  
  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to @post
    else
      flash.now[:alert] = "Post not updated."
      render :edit
    end
  end

  def destroy
      @post.delete
      flash[:notice] = "Post has been deleted."
      redirect_to root_path
  end
  
  def like
    if @post.liked_by current_user
      flash[:notice] = "Post liked!"
      redirect_to root_path
    end
  end
  
  def unlike
    if @post.unliked_by current_user
      flash[:notice] = "Post unliked!"
      redirect_to root_path
    end
  end
  
  private
    def post_params
      params.require(:post).permit(:image, :caption)
    end
    
    def set_post
      @post = Post.find(params[:id])
    end
    
    def owned_post
      unless current_user == @post.user
        flash[:alert] = "This post doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def likers_of(post)
    # votes variable is set to the likes by users.
    votes = post.votes_for.up.by_type(User)
    # set user_names variable as an empty array
    user_names = []
    # unless there are no likes, continue below.
    unless votes.blank?
    # iterate through the voters of each vote (the users who liked the post)
      votes.voters.each do |voter|
        # add the user_name as a link to the array
        user_names.push(link_to voter.user_name, profile_path(voter.user_name), class: 'user-name')
      end
      # present the array as a nice sentence using the as_sentence method and also make it usable within our html.  Then call the like_plural method with the votes variable we set earlier as the argument.
      return user_names.to_sentence.html_safe + like_plural(votes) if votes.count <= 8
      votes.count.to_s + ' people' + like_plural(votes)
    end
  end
  
  def liked_post(post)
    return 'glyphicon-heart' if current_user.voted_for? post
    'glyphicon-heart-empty'
  end
  private
    def like_plural(votes)
      return ' like this' if votes.count > 1
      ' likes this'
    end
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= image_tag "placeholder.jpg", id: 'image-preview', class: 'img-responsive' %>
        <%= simple_form_for @post, html: { multipart: true }  do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image:</h4>
              <%= f.input :image, label: false, id: 'Image', input_html: { onChange: 'loadFile(event)' } %>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.input :caption, label: false, placeholder: "Caption" %>
          </div>
          <div class="form-group text-center">
            <%= f.button :submit, class: 'btn-success btn-block' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_#{post.id}">
  <%= likers_of post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
  <div class="post">
      <div class="post-head">
        <div class="thumb-img">
          <div class="user-name">
  	      <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
          </div>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <div class="post-bottom">
        <%= render 'posts/likes', post: post %>
        <div class="caption">
          <%= post.caption %>
        </div>
        <div class="time-ago">
          <%= time_ago_in_words(post.created_at) %>
        </div>
        <div class="comments" id="comments_#{post.id}">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
        <div class="comment-like-form row">
          <div class="col-sm-1">
            <% if current_user.voted_for? post %>
              <%= link_to '', unlike_post_path(post.id), id: "unlike#{post.id}", class: "glyphicon #{liked_post post}" %>
            <% else %>
              <%= link_to '', like_post_path(post.id), id: "like#{post.id}", class: "glyphicon #{liked_post post}" %>
            <% end %>
          </div>
          <div class="comment-form col-sm-11">
            <%= form_for [post, post.comments.build] do |f| %>
                <%= f.text_field :content, placeholder: 'Add a comment:', class: "comment_content", id: "comment_content_#{post.id}" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/edit.html.erb
<div class="posts-wrapper row">
    <div class="post">
      <div class="image center-block">
        <%= image_tag @post.image(:medium) %>
      </div>
    </div>
</div>
    
<%= render "form" %>

<div class="text-center edit-links">
  <%= link_to "Back", post_path(@post) %>
  |
  <%= link_to "Delete post", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/posts/index.html.erb
<div id="posts">  
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</div>


<div id="paginator" class="text-center">
    <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>
    

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/new.html.erb
<%= render "form" %>
<div class="text-center edit-links">
  <%= link_to "Back", posts_path %>
</div>

app/views/posts/read.html.erb
<h1>Posts#read</h1>
<p>Find me in app/views/posts/read.html.erb</p>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
  <%= link_to "Back", posts_path %>
  <% if current_user.id == @post.user.id %>
    | <%= link_to "Edit post", edit_post_path(@post) %>
  <% end %>
</div>